language: python
python: 3.5
branches:
  only:
  - master
  - /^\d\.\d+$/
  - /^v\d\.\d+\.\d+(rc\d+|dev\d+)?$/
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
install:
  - pip install -U tox twine wheel codecov
script: tox -e $TOX_ENV
after_success:
  - codecov
cache:
  directories:
  - $HOME/.cache/pip
