language: python
python:
  - 2.7
  #- 3.2
  #- 3.3
  - 3.4
  - 3.5
cache: pip
install:
  - pip install -U tox tox-travis twine wheel codecov coverage contextlib2
script:
  - tox
after_success:
  - tox -e codecov
